### ISSUE TITLE
Errno8 : ERROR : Exception "gaierror" occured with message 

### ISSUE THREAD

**Issue by jlavigne76** [leeroybrun/glacier-vault-remove#16]
Hello,

When I try to delete archives on my Glacier vault, I have the following error : ERROR : Exception "gaierror" occured with message "[Errno 8] nodename nor servname provided, or not known".
How can I solve it ?

Regards,

**Comment by leeroybrun** [comment]
Can you please provide me the command you entered to start the removeVault script?

This may be a network or permission related issue.

Have you tried on a different network/computer?

Have you set the correct permissions on Amazon for Glacier? Please see this issue : https://github.com/leeroybrun/glacier-vault-remove/issues/14#issuecomment-160068184

**Comment by jlavigne76** [comment]
Please find the following command line : python removeVault.py eu-central-1 DiskStation-ID_001132234D84_1.
On 169GB, 3,2GB are not deleted and the error message is displayed for every archive.
I try on Wifi Network and Ethernet but not on different computer.
If the script has correctly worked on the previous GB, I think that the permissions are correct on Amazon Glacier.

**Comment by jlavigne76** [comment]
I just try on another computer. I have the following message : 
Traceback (most recent call last):
  File "removeVault.py", line 103, in <module>
    inventory = json.loads(job.get_output().read().decode('utf-8'))
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/glacier/job.py", line 89, in get_output
    byte_range)
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/glacier/layer1.py", line 740, in get_job_output
    response_headers=response_headers)
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/glacier/layer1.py", line 119, in make_request
    raise UnexpectedHTTPResponseError(ok_responses, response)
boto.glacier.exceptions.UnexpectedHTTPResponseError: Expected (200, 206), got (404, {"code":"ResourceNotFoundException","message":"The job ID was not found: T0yZ7mXFmIc2T23UhQ7E6zP8OhPKL3UbLp-IuqcLdov2uTixXrgOnkVcp39qu9qI6dD59xcC6S32tyIm6_7olbsg__oB","type":"Client"})
If it can help you... for me it's not clear...

**Comment by jlavigne76** [comment]
Issue Solved. I don't know how.

**Comment by mattbrictson** [comment]
I'm seeing the same error.

It seems like 99% of deletes work, but every now and then I see:

```
07:49:33 - ERROR : Exception "gaierror" occured with message "[Errno 8] nodename nor servname provided, or not known"
07:49:33 - INFO : Sleep 2 mins before retrying...
07:51:33 - INFO : Retry to remove archive ID : AboTZ_DAfFbThulDZuG9_CJMekdBHGGvw0s1Pm...
07:51:34 - INFO : Successfully removed archive ID : AboTZ_DAfFbThulDZuG9_CJMekdBHGGvw0s1Pm...
```

It always succeeds on the retry, which is interesting.

Any ideas?

**Comment by leeroybrun** [comment]
I don't know exactly why it's happening, but I had this problem too, this is why I implemented the retry.

Maybe we send too much requests to Amazon and it just refuse one from time to time. But the error is strange though...

**Comment by z0ph** [comment]
Hello,

Same problem here 

`21:23:15 - INFO : Sleep 2 mins before retrying...
21:25:15 - INFO : Retry to remove archive ID : cU36du0VKFeubk-gwxPPn5LsaF0wyalSY6qjZOnRJLj8XrwIthv3cNRqjVnvGovVgSjlbPI74iWvj9DCsgEqIiHWhlYIk5pYfipXe7fo-nSBlaH0hBPCaEGXv0syzFbvlFPg
21:25:15 - INFO : Successfully removed archive ID : cU36du0VKFeubk-gwxPPn5LsaF0wyalSY6qjZOnRJLj8XrwIthv3cNRqjVnvGovVgS3J6wI74iWvj9DCsgEqIiHWhlYIk5pYfipXe7fo-nSBlaH0hBPCaEGXv0syzFbvlFPg
21:27:46 - ERROR : Exception "gaierror" occured with message "[Errno 8] nodename nor servname provided, or not known"
21:27:46 - INFO : Sleep 2 mins before retrying...
21:29:46 - INFO : Retry to remove archive ID : EkoIEiTeCdDpwxWWdYjbBVqtwoRH7YhgdQkNt6g7fGZ-BxHb9b9WQYUV4ewI5dWb9lRo0HXsZ2XADYhRX94QBBzw_a2RlS7v8wqpqxwHShrvnCLt-N9_knMt-XymD1yfB0wxw
21:29:48 - INFO : Successfully removed archive ID : EkoIEiTeCdDpwxWWdYjbBVqtwoRH7YhgdQkNt6g7fGZ-BxHb9b9WQYUV4ewI5dWb9lRo0HXsZ2XADYhRX94bGa2RlS7v8wqpqxwHShrvnCLt-N9_knMt-XymD1yfB0wxw
21:32:26 - ERROR : Exception "gaierror" occured with message "[Errno 8] nodename nor servname provided, or not known"
21:32:26 - INFO : Sleep 2 mins before retrying...`

I've launch the following command at : 8 am this morning, the script is still working for 	25866 archives only.

`python removeVault.py eu-west-1 Epona_001132053DFD_1`

ATM, 23903 remaining according to AWS Glacier Console.

**Comment by dkrees** [comment]
I'm getting the same error. 
I get: 

> INFO : Successfully removed archive ID

followed by the error:

> ERROR : Exception "gaierror" occured with message "[Errno 8] nodename nor servname provided, or not known"

Its been going for a few hours now, is it actually working?

**Comment by leeroybrun** [comment]
Yes it should be working.

The error message is not related to the archive successfully removed, but the next one.
The script then wait for 2 mins before retrying, and normally the archive will be successfully removed this time.

Can you confirm that it worked as expected?
Were you able to remove all the archives in your vault?
