### ISSUE TITLE
Exception "gaierror" with "Errno -3"

### ISSUE THREAD

**Issue by sebask** [leeroybrun/glacier-vault-remove#23]
After around 900 succesful removals I end up getting an exception `gaierror` with message `[Errno -3] Try again`. Restarting Docker fixes this, but I start at 0 again.

Full error:
```
19:44:19 - ERROR : Exception "gaierror" occured with message "[Errno -3] Try again"
```

**Comment by sebask** [comment]
After some trial and error I switched to running the tool without Docker. Which worked great. The error above never showed up.

**Comment by leeroybrun** [comment]
Great, thanks for your feedback!
