### ISSUE TITLE
Error: Too Many Open Files

### ISSUE THREAD

**Issue by jensjakob** [leeroybrun/glacier-vault-remove#24]
Hi. I get the error "Too many open files" using Ubuntu Server in a VirtualBox environment.

**Comment by raphael-riel** [comment]
HI @jensjakob,

I managed to resolve this issue by setting higher values for Hard/Soft file descriptors limits.

In my case, on an AmazonLinux (RedHat):

`/etc/security/limits.d/custom.conf`

```
* hard nofile 500000
* soft nofile 500000
```

A reboot/session login/logout may be necessary.
Check this thread for more info (My source):
http://stackoverflow.com/a/24685189/719535

**Comment by leeroybrun** [comment]
Closing as this is quite old. Feel free to let us know if that's still an issue.
