### ISSUE TITLE
Dockerfile installing incorrect version of boto

### ISSUE THREAD

**Issue by stigok** [leeroybrun/glacier-vault-remove#26]
Running the container as described in the readme produces following error
```
$: docker run -v $(pwd)/credentials.json:/app/credentials.json glacier-test eu-central-1 LIST
Traceback (most recent call last):
  File "/app/removeVault.py", line 10, in <module>
    import boto3
ImportError: No module named boto3
```

Dockerfile installs an earlier version of boto than the one being used by the python scripts. Expected version is boto3.

Proposing installing `pip`, then installing `boto3` via `pip`.

**Comment by leeroybrun** [comment]
I merged your pull request, thanks!
