### ISSUE TITLE
Deletes not working?

### ISSUE THREAD

**Issue by dustindclark** [leeroybrun/glacier-vault-remove#28]
I have 411 items at 1.8 TB.  The script takes about 5 hours, then this:

```
23:23:56 - INFO : 12385 Remove archive number 410 of 411, ID : XXX-XXX
23:23:56 - INFO : Removing vault...
23:23:56 - INFO : Resetting dropped connection: glacier.us-east-1.amazonaws.com
23:23:56 - ERROR : Exception "InvalidParameterValueException" occured with message "An error occurred (InvalidParameterValueException) when calling the DeleteVault operation: Vault not empty or recently written to: arn:aws:glacier:us-east-1:XXX:vaults/xxx"
23:23:56 - ERROR : We cant remove the vault now. Please wait some time and try again. You can also remove it from the AWS console, now that all archives have been removed.
```

The count starts a 0, so 410 of 411 is actually correct.  I have "waited some time" (about 24 hours) as instructed, but I still cannot delete my vault on the AWS console.  In fact, the vault is still showing that it was last updated in 2015 and still has 411 archives.  Any ideas on this?

**Comment by raphael-riel** [comment]
Vault Deletion need another pass of inventory before working (Auto-triggered by Glacier upon deleting all files).
Attempt to go back to the console after 4-8h post deletion; the newest inventory should had completed by then and you'll be able to delete the vault via the Web Console.

**Comment by dustindclark** [comment]
@raphael-riel it took close to 48 hours, but it did finally refresh (and then allow deletion) on the AWS console.  Thank you!
