### ISSUE TITLE
Docker image in docker registry.

### ISSUE THREAD

**Issue by jgimeno** [leeroybrun/glacier-vault-remove#31]
Hi! Thank you very much for this software, I have seen that it even has a Dockerfile. I have a suggestion, maybe you can include an image in the docker hub so people don't need to construct in his own machine, install dep, etc.

Have you think about it? :D

**Comment by leeroybrun** [comment]
This is a great suggestion, thanks!

I created the image on Docker Hub some time ago, but forgot to mention it in the README until now.

This is now fixed. :-)
