### ISSUE TITLE
Can`t start deleting

### ISSUE THREAD

**Issue by workchit** [leeroybrun/glacier-vault-remove#38]
Hi!
Thank you very much fo the script! I cant start deleting with the code `python .\removeVault.py eu-west-1 my_vault`. Ubuntu 16.04. Perhaps, it is not an issue, maybe I did something wrong. But when I removed .\ , deleting started. Now it works with `python removeVault.py eu-west-1 my_vault`. Maybe it could be useful for somebody, cause I tried to start 4 hours)))). Thank you!

**Comment by leeroybrun** [comment]
Thanks, I updated the README.
