### ISSUE TITLE
Inventory not ready, sleep for 10 mins...

### ISSUE THREAD

**Issue by robmarkcole** [leeroybrun/glacier-vault-remove#40]
HI 
I repeatedly receive `Inventory not ready, sleep for 10 mins...`, what is the solution?
Thanks

**Comment by leeroybrun** [comment]
It's normal as inventory retrieval can sometimes take hours on Amazon Glacier.
You should let the script running as it wait for the retrieval to complete and then it will perform the removal.

In short, the solution is to wait. :-)
