### ISSUE TITLE
Missing option for forcing new inventory retrieval

### ISSUE THREAD

**Issue by pipozzz** [leeroybrun/glacier-vault-remove#42]
Hello,

1. Maybe there would be cool to have ability for forcing new inventory retrieval if something fail or so, like this happened me yesterday. If you want I can provide you PR.

2. If you do not have time for maintaining this repository, you could move ownership to me and I would maintain it, provide auto pip packaging and also auto docker building if you want.

**Comment by jefferose** [comment]
I'd love to know the answer to this. We have a HUGE inventory (6 million records) and if we have to stop for some reason, removal seems to start from the beginning and run over files already removed.

**Comment by grrowl** [comment]
The inventory won't update for up to 24 hours, so there's no way of telling what was deleted or not until that time is up.

I'd also love an option to force a refetch of the inventory job (although it took several hours for that job to complete for me). I'll try it in 24 hours and hope it refreshes the inventory and I can finally delete the bucket

**Comment by leeroybrun** [comment]
I just updated the script and added a new option to force new/list/select specific inventory retrieval jobs : https://github.com/leeroybrun/glacier-vault-remove#inventory-retrieval-jobs

Let me know if that works for you!
