### ISSUE TITLE
Issues when installing on macOS

### ISSUE THREAD

**Issue by petitpoisson** [leeroybrun/glacier-vault-remove#44]
I can't seem to install the tool on macOS 10.14 (Mojave). Here's the error I get : 

(…) 
Installed /Library/Python/2.7/site-packages/GlacierVaultRemove-0.1-py2.7.egg
Processing dependencies for GlacierVaultRemove==0.1
Searching for urllib3<1.26,>=1.20
Reading https://pypi.python.org/simple/urllib3/
Best match: urllib3 1.25.7
Downloading https://files.pythonhosted.org/packages/ad/fc/54d62fa4fc6e675678f9519e677dfc29b8964278d75333cf142892caf015/urllib3-1.25.7.tar.gz#sha256=f3c5fd51747d450d4dcf6f923c81f78f811aab8205fda64b0aba34a4e48b0745
Processing urllib3-1.25.7.tar.gz
Writing /tmp/easy_install-Gj3a2G/urllib3-1.25.7/setup.cfg
Running urllib3-1.25.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Gj3a2G/urllib3-1.25.7/egg-dist-tmp-CB4YAZ
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error: Setup script exited with error in urllib3 setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

Can you help ?

**Comment by steve-ross** [comment]
@petitpoisson try installing via homebrew:
1. install homebrew: https://brew.sh/
2. install python: https://docs.brew.sh/Homebrew-and-Python

**Comment by leeroybrun** [comment]
This seems to be related to an outdated `setuptools`: https://stackoverflow.com/a/43214011/1160800

The error occurred on my mac too. Using `virtualenv` solved the problem for me, and it's also a good practice so you don't install the dependencies system wide: https://virtualenv.pypa.io/en/latest/

```
pip install --user virtualenv
virtualenv ENV
source ENV/bin/activate
python setup.py install
```
