### ISSUE TITLE
Access via Synology? 

### ISSUE THREAD

**Issue by nreuter** [leeroybrun/glacier-vault-remove#46]
Hi, sorry if this isn't the correct spot for it, i'm trying to get this up & running! 

I have a Synology dS918+ which I installed Docker on.

This is an upgrade for me from a previous Synology, a DS212. Mostly used for photo & video storage.

Anyway, I run an Amazon Glacier Backup via Synology. When I switched NAS devices, it created an entirely new S3 Vault. I'm unable to delete my old vault (from the DS212), because of an error saying, "Vault not empty or recently written to "

After some googling, I found a solution your solution! 

I have successfully setup the Container within my DS918+, but I can't seem to get it to run at all.

I created the requested file (credentials.json) and put them into my /Docker shared folder on the NAS.

But whenever I start the container, it just shuts down immediately.

https://imgur.com/vwMPZkR

I'm not sure what I'm doing wrong, it's probably something super obvious, but i've been googling and trying things for almost 2 hours and made no progress. My guess is maybe it's shutting down because credentials aren't connecting because I didn't put them in the right place? The Docker shared folder where I placed them on my NAS is otherwise empty. I can't run any scripts because the container just shuts down a second after I start it. 

**Edit**: I ended up getting this running via Ubuntu in VMWare Workstation instead of Docker. That worked fine, although after it ran I still don't seem to be able to delete the vault; seems like it may just take some additional time.

**Comment by skchung11** [comment]
I have same issue when running it in Synlogy Docker. Anyone can advise?
