### ISSUE TITLE
Inventory not ready, sleep for 10 mins

### ISSUE THREAD

**Issue by pascar73** [leeroybrun/glacier-vault-remove#49]
I get this error message:

21:04:18 - INFO : Inventory not ready, sleep for 10 mins...

In a loop, even after waiting for 10 minutes several time, there is no progress.
Whta's the issue in this case?

Thanks

**Comment by leeroybrun** [comment]
This is normal. Inventory retrieval can take quite some time, depending on the size of your Glacier Vault.

You just have to let it run and when the inventory is ready on Amazon the script will continue.
