### ISSUE TITLE
boto.glacier.exceptions.UnexpectedHTTPResponseError

### ISSUE THREAD

**Issue by gcraenen** [leeroybrun/glacier-vault-remove#9]
boto.glacier.exceptions.UnexpectedHTTPResponseError

**Comment by leeroybrun** [comment]
When does it happens ? Have you tried again later ?

Maybe it's just a network related error...

**Comment by patricksan** [comment]
got the same problem here.

**Comment by patricksan** [comment]
Just find out it is related to permission. @gcraenen .

**Comment by gcraenen** [comment]
Tried it a few times, while following network and http trafic with wireshark and burpsuite. It seemed that the url redirects to the wrong "place" where the vault is located (directed to eu-ireland while it should have been eu-frankfurt. I was in a hurry so not enough time to fix the code for this. Used another program to do it.
